application: app-ay-n0
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /.*
  static_files: index.html
  upload: index\.html